version: '2'
services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /path/to/certs:/etc/nginx/certs:ro
    ports:
      - "80:80"
      - "443:443"
  nginx-gen:
    container_name: nginx-gen
    image: jwilder/docker-gen
    volumes_from:
      - nginx-proxy
    volumes:
      - /path/to/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    command: "-notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
  nginx-letsencrypt:
    container_name: nginx-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
    volumes_from:
      - nginx-proxy
    volumes:
      - /path/to/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
  nginx-static:
    image: nginx
    container_name: nginx-static
    environment:
      - VIRTUAL_HOST=cookingquests.com
      - LETSENCRYPT_HOST=cookingquests.com
      - LETSENCRYPT_EMAIL=cookingquest@cookingquests.com
    volumes:
     - /root/cookingquest/nginx.conf:/etc/nginx/nginx.conf:ro
     - /root/cookingquest/www:/www
