version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  phoenix:
    image: skender/cookingquests-phoenix
    container_name: phoenix
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "4000"
  koa:
    image: skender/cookingquests-koa
    container_name: koa
    volumes:
      - /app/templates:/templates
    expose:
      - "3001"
  app:
    image: skender/cookingquests-app
    container_name: app
    volumes:
      - /app:/app
  nginx:
    image: skender/cookingquests-nginx
    container_name: nginx
    volumes:
     - /app:/app
     - /etc/letsencrypt:/certs
     - /etc/ssl/certs/dhparam.pem:/dhparam.pem
    ports:
      - "443"
